// Local visual QA only. No accounts, provider calls, maps keys or saved preferences.
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
function previewPage(){
const source=fs.readFileSync(path.join(root,'assets/roxy_list.js'),'utf8');
const scene=source.slice(source.indexOf('  function familyWeatherMode()'),source.indexOf('  async function loadFamilyRadarMetadata('));
const page=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nexo · prueba meteorológica aislada</title><link rel="stylesheet" href="/weather.css"><style>
body{margin:0;padding:20px;font:14px system-ui;background:#f5f1e7;color:#174d36}main{max-width:393px;margin:auto}h1{font:700 23px Georgia}label{display:block;margin:12px 0}select{padding:10px;width:100%}.stage{position:relative;height:630px;background:#e7ede8;border-radius:26px;overflow:hidden}.context{position:absolute;z-index:6;top:70px;left:15px;right:15px;padding:15px;background:#fffdf8;border-radius:24px;font-size:12px}.model-map{position:absolute;inset:0;display:grid;place-content:center;text-align:center;color:#58675e;background:linear-gradient(145deg,#dbe7df,#f4f4e8)}.model-map small{display:block;max-width:230px;margin:9px auto;line-height:1.5}.fake-person{padding:18px;background:#fffdf8;border:2px solid #b68a32;border-radius:18px}.test-footer{position:absolute;z-index:6;bottom:0;left:0;right:0;background:#fffdf8;padding:22px;text-align:center}button{cursor:pointer}
</style><main><h1>Prueba de clima · datos sintéticos</h1><p>Se prueba el mismo código de Nexo. Este fondo no es un mapa real.</p><label>Condición<select id="condition"><option value="storm">Tormenta intensa</option><option value="rain">Lluvia ligera</option><option value="sun">Soleado</option><option value="night">Noche despejada</option><option value="snow">Nieve</option><option value="cloud">Nublado</option><option value="stale">Datos vencidos</option></select></label><div class="stage"><div class="model-map"><div class="fake-person">Marcador de prueba</div><small>Área del mapa: los efectos no interceptan gestos ni botones.</small></div><div id="familyWeatherFx" class="family-weather-fx"></div><div class="context" id="familyWeatherSummary"></div><div id="familyWeatherFxNote" class="family-weather-fx-note"></div><div class="family-map-zoom"><button aria-label="Acercar" id="plus">+</button><button aria-label="Alejar" id="minus">−</button></div><div class="test-footer" id="result">Botones disponibles</div></div></main><script src="/weather-renderer.js"></script><script>
const $=id=>document.getElementById(id);let homeWeather={},familyWeatherGlobeActive=false,familyMap=null,activePanel='family',account={mode:'checking'},commerce={profile:{location_enabled:false}};
const familyClock=value=>new Date(value).toLocaleTimeString('es-US',{hour:'numeric',minute:'2-digit'});
${scene}
function change(){const mode=$('condition').value,code={storm:99,rain:61,sun:0,night:0,snow:75,cloud:3,stale:99}[mode];const valid=new Date(Date.now()-(mode==='stale'?7200000:900000)).toISOString();homeWeather={status:'READY',updated_at:new Date().toISOString(),location:{label:'Ubicación ficticia'},current:{valid_at:valid,code,condition:$('condition').selectedOptions[0].text,temperature:mode==='snow'?28:78,is_day:mode!=='night',interval_seconds:900,precipitation_mm:mode==='storm'?2:mode==='rain'?.1:0,wind_mph:mode==='storm'?25:8,wind_direction_degrees:270,cloud_cover_percent:mode==='sun'||mode==='night'?0:90}};renderFamilyWeatherFx()}
$('condition').addEventListener('change',change);$('plus').addEventListener('click',()=>{$('result').textContent='Acercar: botón recibido'});$('minus').addEventListener('click',()=>{$('result').textContent='Alejar: botón recibido'});change();
</script></html>`;
return page;
}
http.createServer((req,res)=>{res.setHeader('Cache-Control','no-store');if(req.url==='/weather.css'){res.setHeader('Content-Type','text/css');res.end(fs.readFileSync(path.join(root,'assets/roxy_list.css')))}else if(req.url==='/weather-renderer.js'){res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync(path.join(root,'assets/roxy_home_weather_renderer.js')))}else{res.setHeader('Content-Type','text/html; charset=utf-8');res.end(previewPage())}}).listen(8788,'127.0.0.1',()=>process.stdout.write('Isolated Nexo weather QA: http://127.0.0.1:8788/\n'));
